LOCAL_STORAGE_FOLDER = "geojson_data"
ARCGIS_STORAGE_FOLDER = "Mapa de Costas-2024"
WEBMAP_TITLE = "Mapa de Costas 2024"

REPORT_LAYER_NAME = "report"
OVERLAP_LAYER_NAME = "overlap"
NONOVERLAP_LAYER_NAME = "non_overlap"
CLUSTER_LAYER_NAME = "cluster"
FAST_TRACK_LAYER_NAME = "fast_track"
PARCEL_LAYER_NAME = "parcel"
PUT_LAYER_NAME = "PUT"

CRS = 6566
